name: Package Build
on:
  push:
  workflow_dispatch:

env:
  VERSION: "1.0.0"

jobs:
  BuildArm64:
    runs-on: ubuntu-24.04-arm
    container: debian:bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y checkinstall postgresql-server-dev-15

      - name: Build Package
        run: checkinstall -y --pkgversion ${{ env.VERSION }} --install=no --fstrans=no

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgjwt-package-arm64
          path: pgjwt_${{ env.VERSION }}-1_arm64.deb

  BuildAmd64:
    runs-on: ubuntu-24.04
    container: debian:bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y checkinstall postgresql-server-dev-15

      - name: Build Package
        run: checkinstall -y --pkgversion ${{ env.VERSION }} --install=no --fstrans=no

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgjwt-package-amd64
          path: pgjwt_${{ env.VERSION }}-1_amd64.deb

  Release:
    needs: [BuildArm64, BuildAmd64]
    runs-on: ubuntu-24.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.ACTIONS_ACCESS_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ env.VERSION }}"
          files: |
            artifacts/pgjwt-package-arm64/pgjwt_${{ env.VERSION }}-1_arm64.deb
            artifacts/pgjwt-package-amd64/pgjwt_${{ env.VERSION }}-1_amd64.deb
