name: Package Build

on:
  push:
  workflow_dispatch:

env:
  VERSION: "1.0.0"

jobs:
  Build:
    runs-on: ubuntu-24.04-arm
    container: debian:bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y checkinstall postgresql-server-dev-15
      - name: Build Package
        run: |
          checkinstall -y --pkgversion ${{ env.VERSION }} --install=no --fstrans=no
      - name: Create Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ACTIONS_ACCESS_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ env.VERSION }}"
          files: |
            pgjwt_${{ env.VERSION }}-1_arm64.deb